import {
  KitchenIcon,
  WifiIcon,
  WorkspaceIcon,
  ParkingIcon,
  PoolIcon,
  HotTubIcon,
  PetsIcon,
  CameraIcon,
  AlarmIcon,
  OutdoorIcon,
  FanIcon,
  DoorIcon,
  CleanlinessIcon,
  AccuracyIcon,
  CheckinIcon,
  CommunicationIcon,
  LocationIcon,
  ValueIcon,
  ComfortIcon,
  ConditionIcon,
  HospitalityIcon,
  AmenitiesTagIcon,
  CalendarXIcon,
  KeyIcon,
  ShieldIcon,
} from "@/components/icons";
import type { ComponentType, SVGProps } from "react";

export const iconMap: Record<string, ComponentType<SVGProps<SVGSVGElement>>> = {
  kitchen: KitchenIcon,
  wifi: WifiIcon,
  workspace: WorkspaceIcon,
  parking: ParkingIcon,
  pool: PoolIcon,
  hotTub: HotTubIcon,
  pets: PetsIcon,
  camera: CameraIcon,
  alarm: AlarmIcon,
  outdoor: OutdoorIcon,
  fan: FanIcon,
  selfCheckin: DoorIcon,
  cleanliness: CleanlinessIcon,
  accuracy: AccuracyIcon,
  checkin: CheckinIcon,
  communication: CommunicationIcon,
  location: LocationIcon,
  value: ValueIcon,
  comfort: ComfortIcon,
  condition: ConditionIcon,
  hospitality: HospitalityIcon,
  amenities: AmenitiesTagIcon,
  cancellation: CalendarXIcon,
  houseRules: KeyIcon,
  safety: ShieldIcon,
};
